name: osc
description: A simple Open Sound Control (OSC) protocol implementation for Dart.
version: 0.0.2

environment:
  sdk: '>=2.2.2 <3.0.0'

dev_dependencies:
  ansicolor: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.0
